config:
  features:
    ALLOW_PRIVATE_IPS:
      isEnabled: false
    GZIP:
      isEnabled: true
    KYMA_COMPANION:
      config:
        apiBaseUrl: 'https://companion.cp.dev.kyma.cloud.sap'
        tokenUrl: 'https://kymatest.accounts400.ondemand.com/oauth2/token'
